### ISSUE TITLE
Tried to run this on mac but it seems to be not wokrin

### ISSUE THREAD

**Issue by qppaepok** [espionn/trakGrab#1]
Hey, thank you for such script! Any chances youll get it workin for mac users? We would be thankful my guy!

**Comment by espionn** [comment]
Hi!

Are you able to give me any more information about why it doesn't work on
mac?

**Comment by qppaepok** [comment]
It just creates empty folder while it says that "All songs downloaded"

**Comment by espionn** [comment]
should be fixed now :)
